// test after() throwing(e: type_of_an_exception)
using Nemerle.Aop;
using Nemerle.IO;

public class Foo {
  public Meth(): int {
    print("I will just throw an exception\n");
        throw System.Exception();
  }


  public Meth2(): int {
    print("I will not throw any exception\n");
        1
  }

  public static Main(): void {
        try {
            _=Foo().Meth2();
            _=Foo().Meth();
        } catch {
            | _ => print("an exception was caught\n");
        }
  }
}

[aspect()]
public class Aspect {

  after() throwing(e: System.Exception) : execution(Foo.?(): int) {
    if (e != null )
            print("advice\n");
        else
            print(" ")
  }
}

/*
BEGIN-OUTPUT
I will not throw any exception
I will just throw an exception
advice
an exception was caught
END-OUTPUT
*/
