// after() without returning, covers also the case when method throws exception
using Nemerle.Aop;
using Nemerle.IO;

public class Foo {
  public Meth(): int {
    print("I will just throw an exception\n");
        throw System.Exception();
  }

  public static Main(): void {
        try {
            _=Foo().Meth();
        } catch {
            | _ => print("an exception was caught\n");
        }
  }
}

[aspect()]
public class Aspect {

  after(): execution(Foo.Meth(): int) {
    print("advice\n");
  }
}

/*
BEGIN-OUTPUT
I will just throw an exception
advice
an exception was caught
END-OUTPUT
*/
